services:
  backend:
    build:
      context: ./Backend
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm run dev

  frontend:
    build:
      context: ./Frontend
    ports:
      - "5173:5173"
    working_dir: /app
    command: npm run dev
