services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm run dev

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    working_dir: /app
    command: npm run dev
    volumes:
      - ../certs:/app/certs
