-- CreateTable
CREATE TABLE "flight" (
    "id" SERIAL NOT NULL,
    "type" VARCHAR,
    "flightid" INTEGER,
    "timetableid" INTEGER,
    "traffictype" VARCHAR(1),
    "flightnumber" TEXT,
    "diverted" BOOLEAN,
    "nachtvlucht" BOOLEAN,
    "flightcode" INTEGER,
    "flightcodedescription" TEXT,
    "flightcodeiata" TEXT,
    "publicannouncement" BOOLEAN,
    "scheduledutc" TIMESTAMP(3),
    "actualutc" TIMESTAMP(3),
    "scheduledlocal" TIMESTAMP(3),
    "actuallocal" TIMESTAMP(3),
    "bewegingen" INTEGER,
    "parkeerpositie" TEXT,
    "parkeercontract" TEXT,
    "bus" BOOLEAN,
    "gate" INTEGER,
    "bagageband" INTEGER,
    "airporticao" TEXT,
    "airport" TEXT,
    "country" TEXT,
    "viaairporticao" TEXT,
    "viaairport" TEXT,
    "aircraftregistration" TEXT,
    "seats" INTEGER,
    "mtow" INTEGER,
    "aircrafttype" VARCHAR,
    "aircraftdescription" TEXT,
    "eu" BOOLEAN,
    "schengen" BOOLEAN,
    "airlinefullname" TEXT,
    "airlineshortname" VARCHAR,
    "airlineicao" TEXT,
    "airlineiata" TEXT,
    "debiteur" TEXT,
    "debiteurnr" INTEGER,
    "paxmale" INTEGER,
    "paxfemale" INTEGER,
    "paxchild" INTEGER,
    "paxinfant" INTEGER,
    "paxtransitmale" INTEGER,
    "paxtransitfemale" INTEGER,
    "paxtransitchild" INTEGER,
    "paxtransitinfant" INTEGER,
    "crewcabin" INTEGER,
    "crewcockpit" INTEGER,
    "bagsweight" INTEGER,
    "bagstransitweight" DOUBLE PRECISION,
    "bags" INTEGER,
    "bagstransit" INTEGER,
    "afhandelaar" TEXT,
    "forecastpercent" DOUBLE PRECISION,
    "forecastpax" INTEGER,
    "forecastbabys" DOUBLE PRECISION,
    "flightclass" TEXT,
    "datasource" TEXT,
    "totaalpax" INTEGER,
    "terminalpax" INTEGER,
    "totaalpaxbetalend" INTEGER,
    "terminalpaxbetalend" INTEGER,
    "transitpax" INTEGER,
    "transitpaxbetalend" INTEGER,
    "totaalcrew" INTEGER,
    "niks" TEXT,
    "terminalcrew" INTEGER,
    "totaalseats" INTEGER,
    "terminalseats" INTEGER,
    "totaalbags" INTEGER,
    "terminalbags" INTEGER,
    "transitbags" INTEGER,
    "totaalbagsweight" DOUBLE PRECISION,
    "terminalbagsweight" DOUBLE PRECISION,
    "transitbagsweight" DOUBLE PRECISION,
    "runway" TEXT,
    "longitude" DOUBLE PRECISION,
    "elevation" DOUBLE PRECISION,
    "latitude" DOUBLE PRECISION,
    "distancekilometers" DOUBLE PRECISION,
    "direction" TEXT,
    "airportiata" TEXT,
    "forecast" BOOLEAN,
    "parked" BOOLEAN,
    "seizoen" TEXT,
    "feestdag" BOOLEAN,

    CONSTRAINT "flight_pkey" PRIMARY KEY ("id")
);
