name: NodeJS with Gulp

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set variables
      working-directory: backend
      run: |
        touch .env
        echo JWT_SECRET_KEY="This is a secret key" >> .env
        echo API_PORT=3000 >> .env
        DATABASE_PORT=5432 >> .env
        cat .env

    - name: Build
      run: |
        npm install
        cd backend
        npm install
        npm run dev
