name: NodeJS with Gulp

on:
  push:
    branches: ["development", "pipeline"]
  pull_request:
    branches: ["development", "pipeline"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (root)
        run: npm install

      - name: Install dependencies (backend)
        working-directory: backend
        run: npm install

      - name: Install dependencies (frontend)
        working-directory: frontend
        run: npm install

      - name: Build typescript code (backend)
        working-directory: backend
        run: npm run build

      - name: Run and test compiled server (backend)
        working-directory: backend
        shell: bash
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          API_PORT: ${{ secrets.API_PORT }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        run: |
          npm run serve &

          SERVER_PID=$!
          sleep 5

          HTTP_STATUS=$(curl -k -s -o /dev/null -w '%{http_code}' https://localhost:${{ secrets.API_PORT }}/health)

          kill $SERVER_PID

          if [ "$HTTP_STATUS" = "200" ]; then
            echo "✅ Health endpoint responded with 200"
            exit 0
          else
            echo "❌ Health endpoint did not respond with 200, got $HTTP_STATUS"
            exit 1
          fi
