name: NodeJS with Gulp

on:
  push:
    branches: ["development", "pipeline"]
  pull_request:
    branches: ["development", "pipeline"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (root)
        run: npm install

      - name: Install dependencies (backend)
        working-directory: backend
        run: npm install

      - name: Install dependencies (frontend)
        working-directory: frontend
        run: npm install

      - name: Build typescript code (backend)
        working-directory: backend
        run: npm run build

      - name: Login
        working-directory: backend
        shell: bash
        id: login
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}

        run: |
          response=$(curl -s -X POST http://localhost:3000/post/login \
          -H "Content-Type: application/json" \
          -d "{\"username\":\"$USERNAME\", \"password\":\"$PASSWORD\"}")
    
          token=$(echo "$response" | jq -r '.token')

          echo "::add-mask::$token"
          echo "token=$token" >> $GITHUB_OUTPUT
          


      - name: Run and test compiled server (backend)
        working-directory: backend
        shell: bash
      - name: Run and test compiled server (backend)
        working-directory: backend
        shell: bash
        run: |
          echo "Starting backend server"
          npm run serve &
          SERVER_PID=$!
          sleep 5

          echo "Checking /health endpoint with JWT auth..."
          HTTP_STATUS=$(curl -k -s -o /dev/null -w '%{http_code}' \
            -H "Authorization: Bearer ${{ steps.login.outputs.token }}" \
            https://localhost:${{ secrets.API_PORT }}/health)

          kill $SERVER_PID

          if [ "$HTTP_STATUS" = "200" ]; then
            echo "✅ Authenticated health check succeeded with 200"
            exit 0
          else
            echo "❌ Authenticated health check failed, got $HTTP_STATUS"
            exit 1
          fi
